// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

/**
 * Protobuf type {@code com.assignment.protobuf.Animal}
 */
public final class Animal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.assignment.protobuf.Animal)
    AnimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Animal.newBuilder() to construct.
  private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Animal() {
    arriveDate_ = "";
    origin_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Animal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Animal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            regNr_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            arriveDate_ = s;
            break;
          }
          case 29: {

            weight_ = input.readFloat();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            origin_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Animal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Animal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.assignment.protobuf.Animal.class, com.assignment.protobuf.Animal.Builder.class);
  }

  public static final int REGNR_FIELD_NUMBER = 1;
  private long regNr_;
  /**
   * <code>int64 regNr = 1;</code>
   * @return The regNr.
   */
  @java.lang.Override
  public long getRegNr() {
    return regNr_;
  }

  public static final int ARRIVEDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object arriveDate_;
  /**
   * <code>string arriveDate = 2;</code>
   * @return The arriveDate.
   */
  @java.lang.Override
  public java.lang.String getArriveDate() {
    java.lang.Object ref = arriveDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arriveDate_ = s;
      return s;
    }
  }
  /**
   * <code>string arriveDate = 2;</code>
   * @return The bytes for arriveDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArriveDateBytes() {
    java.lang.Object ref = arriveDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arriveDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 3;
  private float weight_;
  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  @java.lang.Override
  public float getWeight() {
    return weight_;
  }

  public static final int ORIGIN_FIELD_NUMBER = 4;
  private volatile java.lang.Object origin_;
  /**
   * <code>string origin = 4;</code>
   * @return The origin.
   */
  @java.lang.Override
  public java.lang.String getOrigin() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      origin_ = s;
      return s;
    }
  }
  /**
   * <code>string origin = 4;</code>
   * @return The bytes for origin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginBytes() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      origin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (regNr_ != 0L) {
      output.writeInt64(1, regNr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arriveDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arriveDate_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      output.writeFloat(3, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, origin_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (regNr_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, regNr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arriveDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, arriveDate_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, origin_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.assignment.protobuf.Animal)) {
      return super.equals(obj);
    }
    com.assignment.protobuf.Animal other = (com.assignment.protobuf.Animal) obj;

    if (getRegNr()
        != other.getRegNr()) return false;
    if (!getArriveDate()
        .equals(other.getArriveDate())) return false;
    if (java.lang.Float.floatToIntBits(getWeight())
        != java.lang.Float.floatToIntBits(
            other.getWeight())) return false;
    if (!getOrigin()
        .equals(other.getOrigin())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGNR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRegNr());
    hash = (37 * hash) + ARRIVEDATE_FIELD_NUMBER;
    hash = (53 * hash) + getArriveDate().hashCode();
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeight());
    hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
    hash = (53 * hash) + getOrigin().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.assignment.protobuf.Animal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Animal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Animal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.Animal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Animal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Animal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.assignment.protobuf.Animal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.assignment.protobuf.Animal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.assignment.protobuf.Animal)
      com.assignment.protobuf.AnimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Animal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.assignment.protobuf.Animal.class, com.assignment.protobuf.Animal.Builder.class);
    }

    // Construct using com.assignment.protobuf.Animal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      regNr_ = 0L;

      arriveDate_ = "";

      weight_ = 0F;

      origin_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Animal_descriptor;
    }

    @java.lang.Override
    public com.assignment.protobuf.Animal getDefaultInstanceForType() {
      return com.assignment.protobuf.Animal.getDefaultInstance();
    }

    @java.lang.Override
    public com.assignment.protobuf.Animal build() {
      com.assignment.protobuf.Animal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.assignment.protobuf.Animal buildPartial() {
      com.assignment.protobuf.Animal result = new com.assignment.protobuf.Animal(this);
      result.regNr_ = regNr_;
      result.arriveDate_ = arriveDate_;
      result.weight_ = weight_;
      result.origin_ = origin_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.assignment.protobuf.Animal) {
        return mergeFrom((com.assignment.protobuf.Animal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.assignment.protobuf.Animal other) {
      if (other == com.assignment.protobuf.Animal.getDefaultInstance()) return this;
      if (other.getRegNr() != 0L) {
        setRegNr(other.getRegNr());
      }
      if (!other.getArriveDate().isEmpty()) {
        arriveDate_ = other.arriveDate_;
        onChanged();
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (!other.getOrigin().isEmpty()) {
        origin_ = other.origin_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.assignment.protobuf.Animal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.assignment.protobuf.Animal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long regNr_ ;
    /**
     * <code>int64 regNr = 1;</code>
     * @return The regNr.
     */
    @java.lang.Override
    public long getRegNr() {
      return regNr_;
    }
    /**
     * <code>int64 regNr = 1;</code>
     * @param value The regNr to set.
     * @return This builder for chaining.
     */
    public Builder setRegNr(long value) {
      
      regNr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 regNr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegNr() {
      
      regNr_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object arriveDate_ = "";
    /**
     * <code>string arriveDate = 2;</code>
     * @return The arriveDate.
     */
    public java.lang.String getArriveDate() {
      java.lang.Object ref = arriveDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arriveDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arriveDate = 2;</code>
     * @return The bytes for arriveDate.
     */
    public com.google.protobuf.ByteString
        getArriveDateBytes() {
      java.lang.Object ref = arriveDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arriveDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arriveDate = 2;</code>
     * @param value The arriveDate to set.
     * @return This builder for chaining.
     */
    public Builder setArriveDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arriveDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arriveDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArriveDate() {
      
      arriveDate_ = getDefaultInstance().getArriveDate();
      onChanged();
      return this;
    }
    /**
     * <code>string arriveDate = 2;</code>
     * @param value The bytes for arriveDate to set.
     * @return This builder for chaining.
     */
    public Builder setArriveDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arriveDate_ = value;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }
    /**
     * <code>float weight = 3;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object origin_ = "";
    /**
     * <code>string origin = 4;</code>
     * @return The origin.
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string origin = 4;</code>
     * @return The bytes for origin.
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string origin = 4;</code>
     * @param value The origin to set.
     * @return This builder for chaining.
     */
    public Builder setOrigin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      origin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigin() {
      
      origin_ = getDefaultInstance().getOrigin();
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 4;</code>
     * @param value The bytes for origin to set.
     * @return This builder for chaining.
     */
    public Builder setOriginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      origin_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.assignment.protobuf.Animal)
  }

  // @@protoc_insertion_point(class_scope:com.assignment.protobuf.Animal)
  private static final com.assignment.protobuf.Animal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.assignment.protobuf.Animal();
  }

  public static com.assignment.protobuf.Animal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Animal>
      PARSER = new com.google.protobuf.AbstractParser<Animal>() {
    @java.lang.Override
    public Animal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Animal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Animal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Animal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.assignment.protobuf.Animal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

