// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public interface AnimalPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.assignment.protobuf.AnimalPart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 regNr = 1;</code>
   * @return The regNr.
   */
  long getRegNr();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int64 animalRef = 3;</code>
   * @return The animalRef.
   */
  long getAnimalRef();

  /**
   * <code>float weight = 4;</code>
   * @return The weight.
   */
  float getWeight();
}
