// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.assignment.protobuf.Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 regNr = 1;</code>
   * @return The regNr.
   */
  long getRegNr();

  /**
   * <code>string arriveDate = 2;</code>
   * @return The arriveDate.
   */
  java.lang.String getArriveDate();
  /**
   * <code>string arriveDate = 2;</code>
   * @return The bytes for arriveDate.
   */
  com.google.protobuf.ByteString
      getArriveDateBytes();

  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>string origin = 4;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 4;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
