// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

/**
 * Protobuf type {@code com.assignment.protobuf.PartPack}
 */
public final class PartPack extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.assignment.protobuf.PartPack)
    PartPackOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartPack.newBuilder() to construct.
  private PartPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartPack() {
    trayRef_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartPack();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartPack(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            packRegNr_ = input.readInt64();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              trayRef_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            trayRef_.addLong(input.readInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              trayRef_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              trayRef_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        trayRef_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_PartPack_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_PartPack_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.assignment.protobuf.PartPack.class, com.assignment.protobuf.PartPack.Builder.class);
  }

  public static final int PACKREGNR_FIELD_NUMBER = 1;
  private long packRegNr_;
  /**
   * <code>int64 packRegNr = 1;</code>
   * @return The packRegNr.
   */
  @java.lang.Override
  public long getPackRegNr() {
    return packRegNr_;
  }

  public static final int TRAYREF_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList trayRef_;
  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @return A list containing the trayRef.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getTrayRefList() {
    return trayRef_;
  }
  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @return The count of trayRef.
   */
  public int getTrayRefCount() {
    return trayRef_.size();
  }
  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @param index The index of the element to return.
   * @return The trayRef at the given index.
   */
  public long getTrayRef(int index) {
    return trayRef_.getLong(index);
  }
  private int trayRefMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (packRegNr_ != 0L) {
      output.writeInt64(1, packRegNr_);
    }
    if (getTrayRefList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(trayRefMemoizedSerializedSize);
    }
    for (int i = 0; i < trayRef_.size(); i++) {
      output.writeInt64NoTag(trayRef_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packRegNr_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, packRegNr_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < trayRef_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(trayRef_.getLong(i));
      }
      size += dataSize;
      if (!getTrayRefList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      trayRefMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.assignment.protobuf.PartPack)) {
      return super.equals(obj);
    }
    com.assignment.protobuf.PartPack other = (com.assignment.protobuf.PartPack) obj;

    if (getPackRegNr()
        != other.getPackRegNr()) return false;
    if (!getTrayRefList()
        .equals(other.getTrayRefList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKREGNR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPackRegNr());
    if (getTrayRefCount() > 0) {
      hash = (37 * hash) + TRAYREF_FIELD_NUMBER;
      hash = (53 * hash) + getTrayRefList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.assignment.protobuf.PartPack parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.PartPack parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.PartPack parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.PartPack parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.PartPack parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.PartPack parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.assignment.protobuf.PartPack prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.assignment.protobuf.PartPack}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.assignment.protobuf.PartPack)
      com.assignment.protobuf.PartPackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_PartPack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_PartPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.assignment.protobuf.PartPack.class, com.assignment.protobuf.PartPack.Builder.class);
    }

    // Construct using com.assignment.protobuf.PartPack.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packRegNr_ = 0L;

      trayRef_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_PartPack_descriptor;
    }

    @java.lang.Override
    public com.assignment.protobuf.PartPack getDefaultInstanceForType() {
      return com.assignment.protobuf.PartPack.getDefaultInstance();
    }

    @java.lang.Override
    public com.assignment.protobuf.PartPack build() {
      com.assignment.protobuf.PartPack result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.assignment.protobuf.PartPack buildPartial() {
      com.assignment.protobuf.PartPack result = new com.assignment.protobuf.PartPack(this);
      int from_bitField0_ = bitField0_;
      result.packRegNr_ = packRegNr_;
      if (((bitField0_ & 0x00000001) != 0)) {
        trayRef_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.trayRef_ = trayRef_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.assignment.protobuf.PartPack) {
        return mergeFrom((com.assignment.protobuf.PartPack)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.assignment.protobuf.PartPack other) {
      if (other == com.assignment.protobuf.PartPack.getDefaultInstance()) return this;
      if (other.getPackRegNr() != 0L) {
        setPackRegNr(other.getPackRegNr());
      }
      if (!other.trayRef_.isEmpty()) {
        if (trayRef_.isEmpty()) {
          trayRef_ = other.trayRef_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTrayRefIsMutable();
          trayRef_.addAll(other.trayRef_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.assignment.protobuf.PartPack parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.assignment.protobuf.PartPack) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long packRegNr_ ;
    /**
     * <code>int64 packRegNr = 1;</code>
     * @return The packRegNr.
     */
    @java.lang.Override
    public long getPackRegNr() {
      return packRegNr_;
    }
    /**
     * <code>int64 packRegNr = 1;</code>
     * @param value The packRegNr to set.
     * @return This builder for chaining.
     */
    public Builder setPackRegNr(long value) {
      
      packRegNr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packRegNr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackRegNr() {
      
      packRegNr_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList trayRef_ = emptyLongList();
    private void ensureTrayRefIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trayRef_ = mutableCopy(trayRef_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @return A list containing the trayRef.
     */
    public java.util.List<java.lang.Long>
        getTrayRefList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(trayRef_) : trayRef_;
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @return The count of trayRef.
     */
    public int getTrayRefCount() {
      return trayRef_.size();
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @param index The index of the element to return.
     * @return The trayRef at the given index.
     */
    public long getTrayRef(int index) {
      return trayRef_.getLong(index);
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @param index The index to set the value at.
     * @param value The trayRef to set.
     * @return This builder for chaining.
     */
    public Builder setTrayRef(
        int index, long value) {
      ensureTrayRefIsMutable();
      trayRef_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @param value The trayRef to add.
     * @return This builder for chaining.
     */
    public Builder addTrayRef(long value) {
      ensureTrayRefIsMutable();
      trayRef_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @param values The trayRef to add.
     * @return This builder for chaining.
     */
    public Builder addAllTrayRef(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureTrayRefIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, trayRef_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 trayRef = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayRef() {
      trayRef_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.assignment.protobuf.PartPack)
  }

  // @@protoc_insertion_point(class_scope:com.assignment.protobuf.PartPack)
  private static final com.assignment.protobuf.PartPack DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.assignment.protobuf.PartPack();
  }

  public static com.assignment.protobuf.PartPack getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartPack>
      PARSER = new com.google.protobuf.AbstractParser<PartPack>() {
    @java.lang.Override
    public PartPack parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartPack(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartPack> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartPack> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.assignment.protobuf.PartPack getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

