// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public interface PartPackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.assignment.protobuf.PartPack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 packRegNr = 1;</code>
   * @return The packRegNr.
   */
  long getPackRegNr();

  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @return A list containing the trayRef.
   */
  java.util.List<java.lang.Long> getTrayRefList();
  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @return The count of trayRef.
   */
  int getTrayRefCount();
  /**
   * <code>repeated int64 trayRef = 2;</code>
   * @param index The index of the element to return.
   * @return The trayRef at the given index.
   */
  long getTrayRef(int index);
}
