// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public final class Shared {
  private Shared() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_protobuf_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_protobuf_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_protobuf_AnimalPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_protobuf_AnimalPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_protobuf_Tray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_protobuf_Tray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_protobuf_PartPack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_protobuf_PartPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014shared.proto\022\027com.assignment.protobuf\"" +
      "K\n\006Animal\022\r\n\005regNr\030\001 \001(\003\022\022\n\narriveDate\030\002" +
      " \001(\t\022\016\n\006weight\030\003 \001(\002\022\016\n\006origin\030\004 \001(\t\"L\n\n" +
      "AnimalPart\022\r\n\005regNr\030\001 \001(\003\022\014\n\004type\030\002 \001(\t\022" +
      "\021\n\tanimalRef\030\003 \001(\003\022\016\n\006weight\030\004 \001(\002\"L\n\004Tr" +
      "ay\022\021\n\ttrayRegNr\030\001 \001(\003\022\016\n\006weight\030\002 \001(\002\022\020\n" +
      "\010partType\030\003 \001(\t\022\017\n\007partRef\030\004 \003(\003\".\n\010Part" +
      "Pack\022\021\n\tpackRegNr\030\001 \001(\003\022\017\n\007trayRef\030\002 \003(\003" +
      "2\237\002\n\025SlaughterhouseService\022S\n\rgetAnimalB" +
      "yId\022\037.com.assignment.protobuf.Animal\032\037.c" +
      "om.assignment.protobuf.Animal\"\000\022X\n\020getAn" +
      "imalsByDate\022\037.com.assignment.protobuf.An" +
      "imal\032\037.com.assignment.protobuf.Animal\"\0000" +
      "\001\022W\n\021getAnimalByOrigin\022\037.com.assignment." +
      "protobuf.Animal\032\037.com.assignment.protobu" +
      "f.Animal\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_assignment_protobuf_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_assignment_protobuf_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_protobuf_Animal_descriptor,
        new java.lang.String[] { "RegNr", "ArriveDate", "Weight", "Origin", });
    internal_static_com_assignment_protobuf_AnimalPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_assignment_protobuf_AnimalPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_protobuf_AnimalPart_descriptor,
        new java.lang.String[] { "RegNr", "Type", "AnimalRef", "Weight", });
    internal_static_com_assignment_protobuf_Tray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_assignment_protobuf_Tray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_protobuf_Tray_descriptor,
        new java.lang.String[] { "TrayRegNr", "Weight", "PartType", "PartRef", });
    internal_static_com_assignment_protobuf_PartPack_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_assignment_protobuf_PartPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_protobuf_PartPack_descriptor,
        new java.lang.String[] { "PackRegNr", "TrayRef", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
