// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public interface TrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.assignment.protobuf.Tray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 trayRegNr = 1;</code>
   * @return The trayRegNr.
   */
  long getTrayRegNr();

  /**
   * <code>float weight = 2;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>string partType = 3;</code>
   * @return The partType.
   */
  java.lang.String getPartType();
  /**
   * <code>string partType = 3;</code>
   * @return The bytes for partType.
   */
  com.google.protobuf.ByteString
      getPartTypeBytes();

  /**
   * <code>int64 partRef = 4;</code>
   * @return The partRef.
   */
  long getPartRef();
}
