// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

/**
 * Protobuf type {@code com.assignment.protobuf.Tray}
 */
public final class Tray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.assignment.protobuf.Tray)
    TrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tray.newBuilder() to construct.
  private Tray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tray() {
    partType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tray();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Tray(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            trayRegNr_ = input.readInt64();
            break;
          }
          case 21: {

            weight_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            partType_ = s;
            break;
          }
          case 32: {

            partRef_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Tray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Tray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.assignment.protobuf.Tray.class, com.assignment.protobuf.Tray.Builder.class);
  }

  public static final int TRAYREGNR_FIELD_NUMBER = 1;
  private long trayRegNr_;
  /**
   * <code>int64 trayRegNr = 1;</code>
   * @return The trayRegNr.
   */
  @java.lang.Override
  public long getTrayRegNr() {
    return trayRegNr_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 2;
  private float weight_;
  /**
   * <code>float weight = 2;</code>
   * @return The weight.
   */
  @java.lang.Override
  public float getWeight() {
    return weight_;
  }

  public static final int PARTTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object partType_;
  /**
   * <code>string partType = 3;</code>
   * @return The partType.
   */
  @java.lang.Override
  public java.lang.String getPartType() {
    java.lang.Object ref = partType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partType_ = s;
      return s;
    }
  }
  /**
   * <code>string partType = 3;</code>
   * @return The bytes for partType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartTypeBytes() {
    java.lang.Object ref = partType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTREF_FIELD_NUMBER = 4;
  private long partRef_;
  /**
   * <code>int64 partRef = 4;</code>
   * @return The partRef.
   */
  @java.lang.Override
  public long getPartRef() {
    return partRef_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trayRegNr_ != 0L) {
      output.writeInt64(1, trayRegNr_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      output.writeFloat(2, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, partType_);
    }
    if (partRef_ != 0L) {
      output.writeInt64(4, partRef_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trayRegNr_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, trayRegNr_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, partType_);
    }
    if (partRef_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, partRef_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.assignment.protobuf.Tray)) {
      return super.equals(obj);
    }
    com.assignment.protobuf.Tray other = (com.assignment.protobuf.Tray) obj;

    if (getTrayRegNr()
        != other.getTrayRegNr()) return false;
    if (java.lang.Float.floatToIntBits(getWeight())
        != java.lang.Float.floatToIntBits(
            other.getWeight())) return false;
    if (!getPartType()
        .equals(other.getPartType())) return false;
    if (getPartRef()
        != other.getPartRef()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAYREGNR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTrayRegNr());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeight());
    hash = (37 * hash) + PARTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPartType().hashCode();
    hash = (37 * hash) + PARTREF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPartRef());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.assignment.protobuf.Tray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Tray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.assignment.protobuf.Tray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.Tray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Tray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.assignment.protobuf.Tray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.assignment.protobuf.Tray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.assignment.protobuf.Tray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.assignment.protobuf.Tray)
      com.assignment.protobuf.TrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Tray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Tray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.assignment.protobuf.Tray.class, com.assignment.protobuf.Tray.Builder.class);
    }

    // Construct using com.assignment.protobuf.Tray.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      trayRegNr_ = 0L;

      weight_ = 0F;

      partType_ = "";

      partRef_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.assignment.protobuf.Shared.internal_static_com_assignment_protobuf_Tray_descriptor;
    }

    @java.lang.Override
    public com.assignment.protobuf.Tray getDefaultInstanceForType() {
      return com.assignment.protobuf.Tray.getDefaultInstance();
    }

    @java.lang.Override
    public com.assignment.protobuf.Tray build() {
      com.assignment.protobuf.Tray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.assignment.protobuf.Tray buildPartial() {
      com.assignment.protobuf.Tray result = new com.assignment.protobuf.Tray(this);
      result.trayRegNr_ = trayRegNr_;
      result.weight_ = weight_;
      result.partType_ = partType_;
      result.partRef_ = partRef_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.assignment.protobuf.Tray) {
        return mergeFrom((com.assignment.protobuf.Tray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.assignment.protobuf.Tray other) {
      if (other == com.assignment.protobuf.Tray.getDefaultInstance()) return this;
      if (other.getTrayRegNr() != 0L) {
        setTrayRegNr(other.getTrayRegNr());
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (!other.getPartType().isEmpty()) {
        partType_ = other.partType_;
        onChanged();
      }
      if (other.getPartRef() != 0L) {
        setPartRef(other.getPartRef());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.assignment.protobuf.Tray parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.assignment.protobuf.Tray) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long trayRegNr_ ;
    /**
     * <code>int64 trayRegNr = 1;</code>
     * @return The trayRegNr.
     */
    @java.lang.Override
    public long getTrayRegNr() {
      return trayRegNr_;
    }
    /**
     * <code>int64 trayRegNr = 1;</code>
     * @param value The trayRegNr to set.
     * @return This builder for chaining.
     */
    public Builder setTrayRegNr(long value) {
      
      trayRegNr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 trayRegNr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayRegNr() {
      
      trayRegNr_ = 0L;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <code>float weight = 2;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }
    /**
     * <code>float weight = 2;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object partType_ = "";
    /**
     * <code>string partType = 3;</code>
     * @return The partType.
     */
    public java.lang.String getPartType() {
      java.lang.Object ref = partType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partType = 3;</code>
     * @return The bytes for partType.
     */
    public com.google.protobuf.ByteString
        getPartTypeBytes() {
      java.lang.Object ref = partType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partType = 3;</code>
     * @param value The partType to set.
     * @return This builder for chaining.
     */
    public Builder setPartType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartType() {
      
      partType_ = getDefaultInstance().getPartType();
      onChanged();
      return this;
    }
    /**
     * <code>string partType = 3;</code>
     * @param value The bytes for partType to set.
     * @return This builder for chaining.
     */
    public Builder setPartTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partType_ = value;
      onChanged();
      return this;
    }

    private long partRef_ ;
    /**
     * <code>int64 partRef = 4;</code>
     * @return The partRef.
     */
    @java.lang.Override
    public long getPartRef() {
      return partRef_;
    }
    /**
     * <code>int64 partRef = 4;</code>
     * @param value The partRef to set.
     * @return This builder for chaining.
     */
    public Builder setPartRef(long value) {
      
      partRef_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 partRef = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartRef() {
      
      partRef_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.assignment.protobuf.Tray)
  }

  // @@protoc_insertion_point(class_scope:com.assignment.protobuf.Tray)
  private static final com.assignment.protobuf.Tray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.assignment.protobuf.Tray();
  }

  public static com.assignment.protobuf.Tray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tray>
      PARSER = new com.google.protobuf.AbstractParser<Tray>() {
    @java.lang.Override
    public Tray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Tray(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Tray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.assignment.protobuf.Tray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

