// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package com.assignment.protobuf;

public interface TrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.assignment.protobuf.Tray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 trayRegNr = 1;</code>
   * @return The trayRegNr.
   */
  long getTrayRegNr();

  /**
   * <code>float weight = 2;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>string partType = 3;</code>
   * @return The partType.
   */
  java.lang.String getPartType();
  /**
   * <code>string partType = 3;</code>
   * @return The bytes for partType.
   */
  com.google.protobuf.ByteString
      getPartTypeBytes();

  /**
   * <code>repeated int64 partRef = 4;</code>
   * @return A list containing the partRef.
   */
  java.util.List<java.lang.Long> getPartRefList();
  /**
   * <code>repeated int64 partRef = 4;</code>
   * @return The count of partRef.
   */
  int getPartRefCount();
  /**
   * <code>repeated int64 partRef = 4;</code>
   * @param index The index of the element to return.
   * @return The partRef at the given index.
   */
  long getPartRef(int index);
}
